### ISSUE TITLE
解析磁力链接获取种子一直在等待，同一个链接迅雷秒开，希望排查下

### ISSUE THREAD

**Issue by nubya** [lib-xdown/xdown#2]
同一个链接迅雷瞬间就解析出种子来，XDown却一直在获取种子，希望排查下。链接是 magnet:?xt=urn:btih:P4H7CIUIJ5FI6MFXGUSVTCMXMJKEYZ73&dn=%e5%9c%b0%e7%8b%b1%e7%94%b7%e7%88%b5%ef%bc%9a%e8%a1%80%e7%9a%87%e5%90%8e%e5%b4%9b%e8%b5%b7%2e%e7%be%8e%e7%89%88%2e720p%2e1080p%2eHD%e4%bf%ae%e6%ad%a3%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97&tr=udp%3a%2f%2f9%2erarbg%2eto%3a2710%2fannounce&tr=udp%3a%2f%2f9%2erarbg%2eme%3a2710%2fannounce&tr=http%3a%2f%2ftr%2ecili001%2ecom%3a8070%2fannounce&tr=http%3a%2f%2ftracker%2etrackerfix%2ecom%3a80%2fannounce&tr=udp%3a%2f%2fopen%2edemonii%2ecom%3a1337&tr=udp%3a%2f%2ftracker%2eopentrackr%2eorg%3a1337%2fannounce&tr=udp%3a%2f%2fp4p%2earenabg%2ecom%3a1337

**Comment by lib-xdown** [comment]
已经修正,请重新下载客户端.
https://github.com/lib-xdown/xdown/commit/7c01b3396b60bd42b2a065048be43d24640d7577

**Comment by lib-xdown** [comment]
![image](https://user-images.githubusercontent.com/52403944/61228398-ce343780-a758-11e9-80a4-1b6255bf6029.png)
更新最新版本,已经解决此问题.

**Comment by nubya** [comment]
好的，我更新试试，感谢！
