### ISSUE TITLE
下载下来的压缩包解压时报错

### ISSUE THREAD

**Issue by machunpo** [lib-xdown/xdown#20]

**Comment by lib-xdown** [comment]
https://raw.githubusercontent.com/lib-xdown/xdown/master/xdown-1.0.0.3.7z.001
https://raw.githubusercontent.com/lib-xdown/xdown/master/xdown-1.0.0.3.7z.002
https://raw.githubusercontent.com/lib-xdown/xdown/master/xdown-1.0.0.3.7z.003
https://raw.githubusercontent.com/lib-xdown/xdown/master/xdown-1.0.0.3.7z.004

下载完成之后用7z解压
